import typography from '../../styles/typography'
import colors from '../../styles/colors'

const styles = {
  container: 'min-h-screen bg-[#F4FBF7] flex flex-col pb-28',

  header: 'px-6 pt-8 pb-4',
  headerTitle: [typography['3xl'], typography.extrabold, 'text-black'].join(' '),

  section: 'px-6 mb-6',
  profileCard: [colors.bg.white, 'rounded-3xl p-5 shadow-sm'].join(' '),
  profileRow: 'flex items-center justify-between gap-3',
  profileInfo: 'flex items-center gap-4 min-w-0',
  avatar: 'w-16 h-16 rounded-full object-cover flex-shrink-0',
  nickname: [typography.xl, typography.bold, 'text-black truncate'].join(' '),
  editButton: [colors.bg.green01, 'rounded-full px-5 py-3 flex-shrink-0'].join(' '),
  editButtonText: [typography.base, typography.bold, colors.text.green].join(' '),

  modeSection: 'px-6 mb-6',
  modeSectionTitle: [typography.lg, typography.bold, 'block mb-3 text-black'].join(' '),
  modeCard: [colors.bg.white, 'rounded-3xl shadow-sm overflow-hidden'].join(' '),
  modeList: 'flex flex-col',
  modeDivider: [colors.bg.gray03, 'h-px mx-5'].join(' '),
  modeButton: 'w-full flex items-center justify-between px-5 py-5 text-left',
  modeButtonActive: [colors.bg.green01, 'w-full flex items-center justify-between px-5 py-5 text-left'].join(' '),
  modeTextGroup: 'flex flex-col gap-1',
  modeTitle: [typography.lg, typography.bold, 'text-black'].join(' '),
  modeDesc: [typography.sm, typography.medium, 'text-[#8E8E93]'].join(' '),
  modeIcon: 'w-6 h-6',

  settingsSection: 'px-6 mb-6',
  settingsSectionTitle: [typography.lg, typography.bold, 'block mb-3 text-black'].join(' '),
  settingsCard: [colors.bg.white, 'rounded-3xl shadow-sm p-5'].join(' '),
  settingsRow: 'flex items-center justify-between gap-4',
  settingsTextGroup: 'flex flex-col gap-1 min-w-0',
  settingsTitle: [typography.base, typography.bold, 'text-black'].join(' '),
  settingsDesc: [typography.sm, typography.medium, 'text-[#8E8E93]'].join(' '),
  toggleTrack: 'w-14 h-8 rounded-full flex items-center px-1 flex-shrink-0 transition-colors',
  toggleTrackOn: colors.bg.green,
  toggleTrackOff: colors.bg.gray03,
  toggleKnob: 'w-6 h-6 rounded-full bg-white shadow-sm transition-transform',
  toggleKnobOn: 'translate-x-6',
  toggleKnobOff: 'translate-x-0',

  etcSection: 'px-6 mb-6',
  etcSectionTitle: [typography.lg, typography.bold, 'block mb-3 text-black'].join(' '),
  etcCard: [colors.bg.white, 'rounded-3xl shadow-sm overflow-hidden'].join(' '),
  etcButton: 'w-full flex items-center gap-3 px-5 py-5 text-left',
  etcTextGroup: 'flex flex-col gap-0.5 flex-1 min-w-0',
  etcTitle: [typography.base, typography.bold, 'text-black'].join(' '),
  etcDesc: [typography.sm, typography.medium, 'text-[#8E8E93]'].join(' '),
  etcRightIcon: 'w-5 h-5 opacity-40',

  logoutButton: 'mx-6 mb-2 py-4 rounded-2xl text-center',
  logoutText: [typography.base, typography.bold, colors.text.gray01].join(' '),
  withdrawLink: 'mx-6 py-2 text-center',
  withdrawLinkText: [typography.sm, typography.medium, 'text-[#B3B3BD]'].join(' '),

  // 하위 화면 공통(프로필 편집, 탈퇴, 친구 관리)
  subContainer: 'min-h-screen bg-white flex flex-col pb-10',
  subHeader: 'flex items-center gap-2 px-4 py-4',
  subBackButton: 'w-11 h-11 -ml-1 rounded-full flex items-center justify-center active:bg-[#F4FBF7]',
  subBackIcon: 'w-6 h-6',
  subHeaderTitle: [typography.lg, typography.bold, 'text-black'].join(' '),

  editForm: 'flex flex-col gap-6 px-6 pt-4',
  editAvatarRow: 'flex flex-col items-center gap-3',
  editAvatarWrapper: 'w-24 h-24 rounded-full overflow-hidden',
  editAvatar: 'w-24 h-24 rounded-full object-cover',
  editAvatarButton: [colors.text.green, typography.base, typography.bold].join(' '),
  editFieldWrapper: 'flex flex-col gap-2',
  editLabel: [typography.base, typography.bold, 'text-black'].join(' '),
  editInput: [colors.bg.gray04, 'rounded-2xl px-5 py-4 outline-none text-black', typography.lg, typography.regular].join(' '),
  editTextarea: [colors.bg.gray04, 'rounded-2xl px-5 py-4 outline-none text-black min-h-[120px] resize-none', typography.base, typography.regular].join(' '),
  editCounter: [typography.sm, typography.medium, 'text-[#B3B3BD] text-right'].join(' '),
  editFieldError: [typography.sm, typography.medium, 'text-red-500'].join(' '),
  editApiError: [typography.sm, typography.medium, 'text-red-500 text-center'].join(' '),
  editSaveButton: [colors.bg.green, 'w-full py-5 rounded-2xl text-center active:opacity-90'].join(' '),
  editSaveButtonText: [typography.lg, typography.bold, 'text-white'].join(' '),

  withdrawBody: 'flex flex-col gap-6 px-6 pt-4',
  withdrawWarning: [typography.base, typography.medium, 'text-[#666666] leading-relaxed'].join(' '),
  withdrawOptionGroup: 'flex flex-col gap-3',
  withdrawOption: [colors.bg.gray04, 'flex items-start gap-3 rounded-2xl px-5 py-4 text-left'].join(' '),
  withdrawOptionSelected: [colors.bg.green01, 'flex items-start gap-3 rounded-2xl px-5 py-4 text-left border-2', colors.border.green].join(' '),
  withdrawRadio: 'w-5 h-5 rounded-full border-2 border-[#D6D6DC] flex-shrink-0 mt-0.5',
  withdrawRadioSelected: [colors.bg.green, 'w-5 h-5 rounded-full flex-shrink-0 mt-0.5'].join(' '),
  withdrawOptionTextGroup: 'flex flex-col gap-1',
  withdrawOptionTitle: [typography.base, typography.bold, 'text-black'].join(' '),
  withdrawOptionDesc: [typography.sm, typography.medium, 'text-[#8E8E93]'].join(' '),
  withdrawSubmitButton: 'w-full py-5 rounded-2xl text-center bg-red-500 active:opacity-90',
  withdrawSubmitText: [typography.lg, typography.bold, 'text-white'].join(' '),

  contactsBody: 'flex flex-col gap-3 px-6 pt-2',
  contactsSectionTitle: [typography.lg, typography.bold, 'block mt-4 mb-1 text-black'].join(' '),
  contactsList: [colors.bg.white, 'rounded-3xl shadow-sm overflow-hidden divide-y divide-[#F0F0F0]'].join(' '),
  contactsRow: 'flex items-center gap-3 px-5 py-4',
  contactsAvatar: ['w-12 h-12 rounded-full object-cover flex-shrink-0', colors.bg.gray04].join(' '),
  contactsNickname: [typography.base, typography.bold, 'text-black flex-1 truncate'].join(' '),
  contactsActionButton: [typography.sm, typography.bold, colors.text.gray01, 'px-3 py-2'].join(' '),

  // 관심사 태그 — 마이페이지 메인의 요약 카드
  tagsSectionHeader: 'flex items-center justify-between mb-3',
  tagsSectionTitle: [typography.lg, typography.bold, 'text-black'].join(' '),
  tagsCard: [colors.bg.white, 'rounded-3xl shadow-sm p-5'].join(' '),
  tagsChipRow: 'flex flex-wrap gap-2',
  tagsDisplayChip: [colors.bg.green01, colors.text.green, 'rounded-full px-4 py-2', typography.base, typography.semibold].join(' '),
  tagsEmptyText: [typography.base, typography.medium, 'text-[#9898A8]'].join(' '),

  // 관심사 태그 편집 — 카테고리를 접어두고 하나씩 펼쳐 선택지를 줄인다(DEV-01)
  tagEditBody: 'flex flex-col gap-4 px-6 pt-4',
  tagEditCounter: [typography.base, typography.bold, colors.text.green].join(' '),
  categoryGroup: 'flex flex-col gap-3',
  categoryButton: [colors.bg.gray04, 'w-full flex items-center justify-between rounded-2xl px-5 py-5 text-left'].join(' '),
  categoryButtonOpen: [colors.bg.green01, 'w-full flex items-center justify-between rounded-2xl px-5 py-5 text-left border-2', colors.border.green].join(' '),
  categoryButtonLeft: 'flex items-center gap-2.5',
  categoryLabel: [typography.lg, typography.bold, 'text-black'].join(' '),
  categoryCount: [colors.bg.green, 'min-w-[24px] h-6 px-1.5 rounded-full flex items-center justify-center text-white', typography.xs, typography.bold].join(' '),
  categoryChevron: 'w-5 h-5 opacity-40',
  categoryChevronOpen: 'w-5 h-5 opacity-70 rotate-90 transition-transform',
  tagPanel: 'flex flex-wrap gap-2.5 px-1 pb-1',
  tagChip: [colors.bg.gray04, 'rounded-full px-4 py-3 text-black', typography.base, typography.semibold].join(' '),
  tagChipSelected: [colors.bg.green, 'rounded-full px-4 py-3 text-white', typography.base, typography.bold].join(' '),
  tagChipDisabled: [colors.bg.gray04, 'rounded-full px-4 py-3 text-[#C7C7CC] opacity-60', typography.base, typography.semibold].join(' '),

  confirmOverlay: 'fixed inset-0 bg-black/40 z-40',
  confirmModal: 'fixed bottom-0 left-0 right-0 z-50 bg-white rounded-t-3xl px-6 pt-6 pb-10 shadow-2xl',
  confirmText: [typography.lg, typography.bold, 'text-black text-center'].join(' '),
  confirmButtons: 'flex items-center gap-3 mt-5',
  confirmNoButton: [
    'flex-1 py-4 rounded-2xl border', colors.border.gray03,
    'flex items-center justify-center text-black active:opacity-70',
    typography.base, typography.medium,
  ].join(' '),
  confirmYesButton: [
    'flex-1 py-4 rounded-2xl', colors.bg.green,
    'flex items-center justify-center text-white active:opacity-80',
    typography.base, typography.bold,
  ].join(' '),

  overlay: 'fixed inset-0 bg-black/40 z-40',
  bottomSheet: 'fixed bottom-0 left-0 right-0 z-50 bg-white rounded-t-3xl px-6 pt-6 pb-10 shadow-2xl transition-transform',
  bottomSheetOpen: 'translate-y-0',
  sheetHandle: 'w-10 h-1.5 rounded-full bg-[#EBEBEF] mx-auto mb-5',
  sheetTitle: [typography.sm, typography.bold, colors.text.green, 'block text-center mb-2'].join(' '),
  sheetTextGroup: 'flex flex-col items-center gap-1 mb-6',
  sheetQuestion: [typography.xl, typography.bold, 'text-black text-center'].join(' '),
  sheetQuestionHighlight: colors.text.green,
  sheetDesc: [typography.sm, typography.medium, 'text-[#8E8E93] text-center'].join(' '),
  sheetConfirmButton: [colors.bg.green, 'w-full py-5 rounded-2xl text-center active:opacity-90 mb-3'].join(' '),
  sheetConfirmText: [typography.lg, typography.bold, 'text-white'].join(' '),
  sheetCancelButton: 'w-full py-3 text-center',
  sheetCancelText: [typography.base, typography.medium, colors.text.gray01].join(' '),
  errorText: [typography.sm, typography.medium, 'text-red-500 text-center mb-3'].join(' '),
}

export default styles
